// Contenu de révision TOEIC : vocabulaire, fiches de grammaire et questions
// d'entraînement écrites pour l'app (dans le style des parties de l'examen,
// ce ne sont pas des questions officielles).

/* ---------- Les parties de l'examen ---------- */

export const TOEIC_PARTS = {
  p1: { label: 'Partie 1 · Photos', section: 'L', n: 6 },
  p2: { label: 'Partie 2 · Questions-réponses', section: 'L', n: 25, tip: 'Écoute surtout le premier mot (Who, When, Where, Why, How…) : il annonce le type de réponse. Méfie-toi des réponses qui répètent un mot de la question, c’est souvent un piège.' },
  p3: { label: 'Partie 3 · Conversations', section: 'L', n: 39, tip: 'Lis les questions AVANT d’écouter. Les réponses arrivent dans l’ordre des questions.' },
  p4: { label: 'Partie 4 · Exposés', section: 'L', n: 30, tip: 'Annonces, messages, publicités : repère qui parle, à qui, et ce qu’on demande de faire.' },
  p5: { label: 'Partie 5 · Phrases à compléter', section: 'R', n: 30, tip: 'Regarde d’abord les 4 réponses : si ce sont des formes du même mot, c’est une question de grammaire, inutile de lire toute la phrase. Vise 20 secondes par question.' },
  p6: { label: 'Partie 6 · Textes à trous', section: 'R', n: 16, tip: 'Lis la phrase avant ET après le trou : le temps du verbe ou le connecteur dépend souvent du contexte.' },
  p7: { label: 'Partie 7 · Compréhension écrite', section: 'R', n: 54, tip: 'Lis la question puis cherche le passage qui y répond (scanning). Les bonnes réponses reformulent le texte avec des synonymes.' },
};

export const TOEIC_LEVELS = [
  { min: 945, label: 'C1', text: 'Utilisateur expérimenté' },
  { min: 785, label: 'B2', text: 'Indépendant avancé — demandé pour beaucoup de postes' },
  { min: 550, label: 'B1', text: 'Indépendant — souvent exigé pour valider un diplôme' },
  { min: 225, label: 'A2', text: 'Élémentaire' },
  { min: 0, label: 'A1', text: 'Débutant' },
];

/* ---------- Vocabulaire (par thème) ---------- */

export const VOCAB_THEMES = {
  bureau: '🏢 Bureau',
  rh: '👥 RH & emploi',
  reunion: '📅 Réunions',
  finance: '💶 Finance',
  commerce: '🛒 Ventes & clients',
  voyage: '✈️ Voyages',
  logistique: '📦 Commandes & livraisons',
  restau: '🍽️ Restaurant & événements',
  pieges: '⚠️ Faux amis',
};

// [anglais, français, exemple]
const V = {
  bureau: [
    ['stationery', 'fournitures de bureau', 'Please order more stationery for the reception desk.'],
    ['to file (a document)', 'classer (un document)', 'Could you file these invoices by date?'],
    ['deadline', 'date limite, échéance', 'The deadline for the report is Friday noon.'],
    ['to postpone', 'reporter', 'The meeting has been postponed until next week.'],
    ['supervisor', 'responsable, superviseur', 'Ask your supervisor to sign the form.'],
    ['colleague / coworker', 'collègue', 'My coworker will cover my shift tomorrow.'],
    ['to be in charge of', 'être responsable de', 'Ms. Lee is in charge of the training program.'],
    ['memo', 'note de service', 'A memo was sent to all staff about the new policy.'],
    ['to photocopy', 'photocopier', 'I need to photocopy the contract before the meeting.'],
    ['out of order', 'en panne', 'The printer on the third floor is out of order.'],
    ['extension (number)', 'numéro de poste', 'You can reach me at extension 214.'],
    ['to update', 'mettre à jour', 'Please update the client list by tomorrow.'],
    ['workload', 'charge de travail', 'Her workload has increased since the merger.'],
    ['headquarters', 'siège social', 'Our headquarters are located in Chicago.'],
    ['branch', 'succursale, agence', 'The bank is opening a new branch downtown.'],
    ['to forward', 'transférer, faire suivre', 'I will forward you the email right away.'],
    ['attachment', 'pièce jointe', 'Please find the schedule in the attachment.'],
    ['to remind', 'rappeler (à qqn)', 'Remind me to call the supplier this afternoon.'],
    ['spreadsheet', 'tableur, feuille de calcul', 'The figures are in the shared spreadsheet.'],
    ['to be on leave', 'être en congé', 'Mr. Park is on leave until the 15th.'],
  ],
  rh: [
    ['applicant / candidate', 'candidat(e)', 'We received over 200 applicants for the position.'],
    ['to apply for', 'postuler à', 'She applied for the marketing manager position.'],
    ['résumé / CV', 'CV', 'Please send your résumé and a cover letter.'],
    ['job opening / vacancy', 'poste à pourvoir', 'There is a job opening in the accounting department.'],
    ['to hire', 'embaucher', 'The company plans to hire 30 new employees.'],
    ['to lay off', 'licencier (économique)', 'The factory had to lay off 50 workers.'],
    ['to resign', 'démissionner', 'He resigned to start his own business.'],
    ['to retire', 'prendre sa retraite', 'Mrs. Brown will retire at the end of the year.'],
    ['promotion', 'promotion', 'She got a promotion after only two years.'],
    ['salary / wage', 'salaire', 'The salary depends on experience.'],
    ['benefits', 'avantages sociaux', 'The benefits include health insurance and a pension plan.'],
    ['qualified', 'qualifié', 'Only qualified candidates will be contacted.'],
    ['requirement', 'exigence, condition requise', 'A degree in finance is a requirement for this job.'],
    ['interview', 'entretien', 'Your interview is scheduled for Monday at 10 a.m.'],
    ['probation period', 'période d’essai', 'New staff have a three-month probation period.'],
    ['full-time / part-time', 'temps plein / temps partiel', 'We are looking for a part-time receptionist.'],
    ['performance review', 'entretien annuel d’évaluation', 'Performance reviews take place every December.'],
    ['personnel', 'le personnel', 'All personnel must wear their badge.'],
    ['to train', 'former', 'Experienced staff will train the new recruits.'],
    ['reference', 'recommandation, référence', 'Please provide two professional references.'],
  ],
  reunion: [
    ['agenda', 'ordre du jour', 'The first item on the agenda is the budget.'],
    ['to attend', 'assister à', 'All managers are expected to attend the meeting.'],
    ['minutes', 'compte rendu (de réunion)', 'Kim will take the minutes today.'],
    ['to chair', 'présider', 'The director will chair the annual meeting.'],
    ['to reschedule', 'reprogrammer', 'Can we reschedule our call to Thursday?'],
    ['conference call', 'conférence téléphonique', 'We have a conference call with the Tokyo office.'],
    ['to brainstorm', 'réfléchir en groupe', 'Let’s brainstorm ideas for the campaign.'],
    ['proposal', 'proposition', 'The board approved the proposal.'],
    ['to approve', 'approuver', 'The budget must be approved by Friday.'],
    ['presentation', 'présentation', 'He gave an excellent presentation on sales trends.'],
    ['handout', 'document distribué', 'Please take a handout before you sit down.'],
    ['to go over', 'passer en revue', 'Let’s go over the main points again.'],
    ['to be available', 'être disponible', 'Are you available on Tuesday afternoon?'],
    ['conference room', 'salle de réunion', 'The conference room is booked until 3 p.m.'],
    ['to reach an agreement', 'parvenir à un accord', 'The two sides finally reached an agreement.'],
    ['board of directors', 'conseil d’administration', 'The board of directors meets quarterly.'],
    ['to call off', 'annuler', 'The meeting was called off because of the storm.'],
    ['feedback', 'retour, avis', 'Thank you for your feedback on the project.'],
    ['to summarize', 'résumer', 'Could you summarize the discussion?'],
    ['quarterly', 'trimestriel', 'The quarterly results will be presented tomorrow.'],
  ],
  finance: [
    ['invoice', 'facture', 'The invoice must be paid within 30 days.'],
    ['budget', 'budget', 'The project is over budget.'],
    ['revenue', 'chiffre d’affaires, recettes', 'Revenue rose by 12% this year.'],
    ['profit', 'bénéfice', 'The company made a record profit.'],
    ['loss', 'perte', 'The store reported a loss for the second quarter.'],
    ['expense', 'dépense', 'Travel expenses will be reimbursed.'],
    ['to reimburse', 'rembourser', 'You will be reimbursed within two weeks.'],
    ['receipt', 'reçu, ticket de caisse', 'Keep your receipts for the expense report.'],
    ['estimate / quote', 'devis', 'We asked three contractors for a quote.'],
    ['accountant', 'comptable', 'Our accountant prepares the tax returns.'],
    ['accounting department', 'service comptabilité', 'Send the form to the accounting department.'],
    ['shareholder', 'actionnaire', 'Shareholders will vote on the merger.'],
    ['merger', 'fusion', 'The merger created the largest firm in the sector.'],
    ['to invest', 'investir', 'They plan to invest in renewable energy.'],
    ['loan', 'prêt', 'The bank approved our loan application.'],
    ['to afford', 'avoir les moyens de', 'We cannot afford a new office this year.'],
    ['outstanding (payment)', 'impayé, en attente', 'There is an outstanding balance of $300.'],
    ['fee', 'frais, honoraires', 'There is no fee for online transfers.'],
    ['financial statement', 'état financier', 'The financial statements are audited every year.'],
    ['to cut costs', 'réduire les coûts', 'The plan aims to cut costs by 10%.'],
  ],
  commerce: [
    ['customer / client', 'client(e)', 'Customer satisfaction is our priority.'],
    ['discount', 'réduction, remise', 'Members get a 15% discount.'],
    ['to purchase', 'acheter', 'You can purchase tickets online.'],
    ['warranty', 'garantie', 'The laptop comes with a two-year warranty.'],
    ['refund', 'remboursement', 'You can get a full refund within 30 days.'],
    ['to exchange', 'échanger', 'Can I exchange this shirt for a larger size?'],
    ['in stock / out of stock', 'en stock / en rupture', 'This model is currently out of stock.'],
    ['complaint', 'réclamation, plainte', 'We take every complaint seriously.'],
    ['to launch', 'lancer', 'The company will launch its new phone in May.'],
    ['competitor', 'concurrent', 'Our prices are lower than our competitors’.'],
    ['market share', 'part de marché', 'They increased their market share in Asia.'],
    ['advertisement / ad', 'publicité, annonce', 'We placed an ad in the local newspaper.'],
    ['survey', 'enquête, sondage', 'Please complete this short customer survey.'],
    ['sales representative', 'commercial(e)', 'A sales representative will contact you.'],
    ['to negotiate', 'négocier', 'We negotiated a better price with the supplier.'],
    ['contract', 'contrat', 'Please sign and return the contract.'],
    ['to renew', 'renouveler', 'Don’t forget to renew your subscription.'],
    ['loyal customer', 'client fidèle', 'We offer gifts to our loyal customers.'],
    ['brochure / catalog', 'brochure / catalogue', 'Our new catalog is available online.'],
    ['sale', 'vente ; soldes', 'All winter coats are on sale this week.'],
  ],
  voyage: [
    ['itinerary', 'itinéraire, programme', 'Your itinerary has been emailed to you.'],
    ['to book / to reserve', 'réserver', 'I booked a room for three nights.'],
    ['boarding pass', 'carte d’embarquement', 'Please show your boarding pass at the gate.'],
    ['departure / arrival', 'départ / arrivée', 'The departure time has changed.'],
    ['delay / to be delayed', 'retard / être retardé', 'Our flight was delayed by two hours.'],
    ['to cancel', 'annuler', 'The train was cancelled due to the strike.'],
    ['luggage / baggage', 'bagages', 'Each passenger may bring one piece of luggage.'],
    ['carry-on bag', 'bagage cabine', 'Carry-on bags must fit under the seat.'],
    ['round-trip ticket', 'billet aller-retour', 'A round-trip ticket costs $450.'],
    ['one-way ticket', 'aller simple', 'I only need a one-way ticket.'],
    ['to check in', 'enregistrer ; s’enregistrer à l’hôtel', 'You can check in from 2 p.m.'],
    ['to check out', 'quitter l’hôtel, régler la note', 'Check-out time is 11 a.m.'],
    ['accommodation', 'hébergement', 'Accommodation is included in the price.'],
    ['fare', 'prix du billet', 'Bus fares will increase next month.'],
    ['business trip', 'voyage d’affaires', 'She is on a business trip in Seoul.'],
    ['travel agency', 'agence de voyages', 'I booked the tour through a travel agency.'],
    ['customs', 'douane', 'We went through customs quickly.'],
    ['layover / stopover', 'escale', 'There is a three-hour layover in Dubai.'],
    ['aisle seat / window seat', 'place couloir / hublot', 'I would prefer an aisle seat.'],
    ['to pick someone up', 'aller chercher qqn', 'A driver will pick you up at the airport.'],
  ],
  logistique: [
    ['order', 'commande', 'Your order will be shipped tomorrow.'],
    ['to ship', 'expédier', 'We ship to over 40 countries.'],
    ['shipment', 'livraison, envoi', 'The shipment arrived damaged.'],
    ['delivery', 'livraison', 'Delivery is free for orders over $50.'],
    ['supplier / vendor', 'fournisseur', 'We are looking for a new supplier.'],
    ['warehouse', 'entrepôt', 'The goods are stored in our warehouse.'],
    ['inventory', 'stock ; inventaire', 'We check the inventory every month.'],
    ['tracking number', 'numéro de suivi', 'Use the tracking number to follow your package.'],
    ['to deliver', 'livrer', 'The furniture will be delivered on Monday.'],
    ['package / parcel', 'colis', 'A package arrived for you this morning.'],
    ['backorder', 'commande en attente (rupture)', 'This item is on backorder until June.'],
    ['to dispatch', 'expédier, envoyer', 'Orders are dispatched within 24 hours.'],
    ['damaged', 'endommagé', 'Two of the boxes were damaged.'],
    ['to replace', 'remplacer', 'We will replace the faulty item at no cost.'],
    ['shipping costs', 'frais de port', 'Shipping costs are calculated at checkout.'],
    ['bulk order', 'commande en gros', 'We offer discounts on bulk orders.'],
    ['manufacturer', 'fabricant', 'Contact the manufacturer for repairs.'],
    ['assembly line', 'chaîne de montage', 'The new assembly line doubled production.'],
    ['to run out of', 'être à court de', 'We have run out of printer paper.'],
    ['estimated delivery date', 'date de livraison prévue', 'The estimated delivery date is May 3.'],
  ],
  restau: [
    ['reservation', 'réservation', 'I’d like to make a reservation for four.'],
    ['catering', 'traiteur, restauration', 'The catering company will provide lunch.'],
    ['banquet', 'banquet', 'The awards banquet starts at 7 p.m.'],
    ['venue', 'lieu (d’un événement)', 'The venue can hold 300 guests.'],
    ['to host', 'organiser, accueillir', 'Our company will host the conference this year.'],
    ['guest', 'invité, client', 'Guests are asked to arrive by 6:30.'],
    ['refreshments', 'rafraîchissements, collation', 'Refreshments will be served after the talk.'],
    ['to register', 's’inscrire', 'Please register online before May 1.'],
    ['registration fee', 'frais d’inscription', 'The registration fee includes lunch.'],
    ['keynote speaker', 'conférencier principal', 'The keynote speaker is a famous economist.'],
    ['to be sold out', 'être complet, épuisé', 'The concert is already sold out.'],
    ['the bill / the check', 'l’addition', 'Could we have the check, please?'],
    ['tip', 'pourboire', 'Service is included, so no tip is necessary.'],
    ['dish', 'plat', 'The chef’s special dish is grilled salmon.'],
    ['to recommend', 'recommander', 'What would you recommend for dessert?'],
    ['attendee / participant', 'participant(e)', 'Each attendee will receive a badge.'],
    ['workshop', 'atelier', 'The workshop on leadership is full.'],
    ['to be held', 'avoir lieu', 'The trade fair will be held in March.'],
    ['trade fair / trade show', 'salon professionnel', 'We will have a booth at the trade show.'],
    ['to set up', 'installer, mettre en place', 'Staff will set up the chairs before 9.'],
  ],
  pieges: [
    ['actually', 'en fait (≠ actuellement)', 'Actually, the meeting is at 3, not 2.'],
    ['currently', 'actuellement', 'We are currently hiring new staff.'],
    ['eventually', 'finalement (≠ éventuellement)', 'Eventually, they signed the contract.'],
    ['library', 'bibliothèque (≠ librairie)', 'The library is open until 8 p.m.'],
    ['bookstore', 'librairie', 'I bought the guide at the bookstore.'],
    ['to attend', 'assister à (≠ attendre)', 'Did you attend the workshop?'],
    ['to wait for', 'attendre', 'Please wait for the manager.'],
    ['sensible', 'raisonnable (≠ sensible)', 'That is a sensible decision.'],
    ['sensitive', 'sensible', 'This information is sensitive.'],
    ['to achieve', 'réaliser, atteindre (≠ achever)', 'We achieved our sales target.'],
    ['to realize', 'se rendre compte', 'I realized I had forgotten my badge.'],
    ['lecture', 'conférence, cours magistral (≠ lecture)', 'The lecture on economics was fascinating.'],
    ['reading', 'lecture', 'Reading reports is part of my job.'],
    ['to assist', 'aider (≠ assister à)', 'Can I assist you with your luggage?'],
    ['delay', 'retard (≠ délai)', 'Sorry for the delay in replying.'],
    ['to control', 'maîtriser, diriger (≠ contrôler)', 'We must control costs.'],
    ['to check', 'contrôler, vérifier', 'Please check the figures again.'],
    ['occasion', 'circonstance (≠ occasion = bargain)', 'This is a special occasion.'],
    ['bargain', 'bonne affaire', 'At $20, this jacket is a bargain.'],
    ['to propose', 'proposer (formel) ; demander en mariage', 'I propose that we vote now.'],
  ],
};

export const VOCAB = Object.entries(V).flatMap(([theme, rows]) =>
  rows.map(([en, fr, ex], i) => ({ id: `${theme}-${i + 1}`, theme, en, fr, ex })),
);

/* ---------- Fiches de grammaire ---------- */

export const GRAMMAR = [
  {
    id: 'formes',
    title: 'Nom, adjectif, adverbe ou verbe ?',
    emoji: '🧩',
    rule: 'La question la plus fréquente de la partie 5 : 4 formes du même mot. Repère la place du trou.',
    points: [
      'Après un déterminant (the, a, his, our…) ou un adjectif → un NOM : « the <b>success</b> of the project ».',
      'Devant un nom ou après be / become / seem → un ADJECTIF : « a <b>successful</b> launch », « she is <b>reliable</b> ».',
      'Devant un verbe, un adjectif, ou en fin de phrase → un ADVERBE (souvent en -ly) : « carefully reviewed », « extremely busy ».',
      'Suffixes de noms : -tion, -ment, -ness, -ity, -ance, -er/-or (personne). Adjectifs : -ful, -ive, -able, -ous, -al, -ent.',
    ],
    trap: 'Une personne ≠ une chose : « an applicant » (un candidat) / « an application » (une candidature).',
  },
  {
    id: 'temps',
    title: 'Les temps des verbes',
    emoji: '⏰',
    rule: 'Cherche l’indice de temps dans la phrase : il décide de la réponse.',
    points: [
      '<b>yesterday, last week, ago, in 2019</b> → prétérit : « We <b>signed</b> the deal last week ».',
      '<b>since, for, already, yet, so far, recently</b> → present perfect : « She <b>has worked</b> here since 2020 ».',
      '<b>tomorrow, next month, soon</b> → futur (will / be going to) ou présent progressif pour un rendez-vous prévu.',
      '<b>every day, usually, always</b> → présent simple : « The store <b>opens</b> at 9 every day ».',
      '<b>by the time + passé</b> → past perfect : « The train <b>had left</b> by the time we arrived ».',
      'Après when / if / as soon as / before / after à sens futur → présent : « when the order <b>arrives</b> » (jamais « will arrive »).',
    ],
    trap: '« for » (pendant une durée) ≠ « since » (depuis un point de départ) : for three years / since 2021.',
  },
  {
    id: 'accord',
    title: 'Accord sujet-verbe',
    emoji: '🤝',
    rule: 'Trouve le vrai sujet : le verbe s’accorde avec lui, pas avec le nom juste avant.',
    points: [
      '« The list of candidates <b>is</b> ready » : le sujet est « list » (singulier).',
      'each, every, everyone, nobody → singulier : « Each employee <b>has</b> a badge ».',
      'Sujet à la 3e personne du singulier au présent → verbe en -s : « The manager <b>approves</b> ».',
      'a number of + pluriel → verbe au pluriel ; the number of → singulier.',
    ],
    trap: 'Les noms comme « news », « information », « equipment », « furniture », « advice » sont indénombrables : jamais de -s.',
  },
  {
    id: 'passif',
    title: 'Voix active ou passive ?',
    emoji: '🔁',
    rule: 'Si le sujet SUBIT l’action, il faut le passif : be + participe passé.',
    points: [
      '« The report <b>was written</b> by Ms. Kim » : le rapport ne s’écrit pas tout seul.',
      'Le passif suit le temps de be : is done / was done / has been done / will be done.',
      'Un complément d’objet direct après le trou → plutôt actif : « The company <b>hired</b> 20 people ».',
      'Expressions fréquentes : be located in, be required to, be expected to, be scheduled for.',
    ],
    trap: '« be + -ing » (progressif, actif) ≠ « be + participe passé » (passif) : is preparing ≠ is prepared.',
  },
  {
    id: 'prep',
    title: 'Les prépositions',
    emoji: '📍',
    rule: 'Temps, lieu et expressions figées : à apprendre par cœur.',
    points: [
      '<b>at</b> + heure (at 9 a.m.), <b>on</b> + jour / date (on Monday, on May 3), <b>in</b> + mois / année / saison (in June, in 2025).',
      '<b>by</b> = au plus tard (by Friday) ; <b>until</b> = jusqu’à (open until 6) ; <b>within</b> = dans un délai de (within 30 days).',
      '<b>during</b> + nom (during the meeting) ; <b>while</b> + sujet + verbe (while I was waiting).',
      'Expressions : responsible <b>for</b>, interested <b>in</b>, depend <b>on</b>, comply <b>with</b>, in charge <b>of</b>, apply <b>for</b> (un poste) / <b>to</b> (une entreprise).',
    ],
    trap: '« despite / in spite of » + nom ; « although » + sujet + verbe. Même sens, construction différente.',
  },
  {
    id: 'conj',
    title: 'Connecteurs logiques',
    emoji: '🔗',
    rule: 'Lis le sens des deux parties : opposition, cause, conséquence ou ajout ?',
    points: [
      'Opposition : although, even though, whereas + phrase ; however (en début de phrase, suivi d’une virgule) ; despite + nom.',
      'Cause : because, since, as + phrase ; because of, due to, owing to + nom.',
      'Conséquence : so, therefore, as a result, consequently.',
      'Ajout : moreover, furthermore, in addition, also. Condition : unless (= if… not), provided that, as long as.',
    ],
    trap: '« because » + phrase, « because of » + nom : because the weather was bad / because of the bad weather.',
  },
  {
    id: 'pronoms',
    title: 'Les pronoms',
    emoji: '👤',
    rule: 'Sujet, complément, possessif ou réfléchi ? Regarde la fonction du trou.',
    points: [
      'Sujet : I, you, he, she, it, we, they. Complément : me, you, him, her, it, us, them.',
      'Devant un nom → adjectif possessif : <b>their</b> office. Seul → pronom possessif : the office is <b>theirs</b>.',
      'Réfléchi (myself, themselves) quand sujet et complément sont la même personne, ou pour insister : « She prepared it <b>herself</b> ».',
      '« by + réfléchi » = seul, sans aide : by himself.',
    ],
    trap: '« its » (possessif) ≠ « it’s » (= it is).',
  },
  {
    id: 'compar',
    title: 'Comparatifs et superlatifs',
    emoji: '📈',
    rule: '« than » → comparatif ; « the … of / in » → superlatif.',
    points: [
      'Mots courts : cheaper than / the cheapest. Mots longs : more efficient than / the most efficient.',
      'Irréguliers : good → better → the best ; bad → worse → the worst ; far → farther / further.',
      '« as + adjectif + as » pour l’égalité : as fast as.',
      '« the + comparatif…, the + comparatif » : The sooner, the better.',
    ],
    trap: 'Après « one of the » → superlatif + nom pluriel : one of the largest companies.',
  },
  {
    id: 'gerinf',
    title: 'Verbe + -ing ou to + verbe ?',
    emoji: '🎯',
    rule: 'Certains verbes sont suivis de -ing, d’autres de to + base verbale.',
    points: [
      'Verbe + <b>-ing</b> : enjoy, avoid, consider, finish, suggest, recommend, mind, keep, look forward to.',
      'Verbe + <b>to</b> : want, plan, decide, hope, agree, offer, refuse, need, expect, manage, afford.',
      'Après une préposition → toujours -ing : « before <b>leaving</b> », « interested in <b>joining</b> ».',
      '« in order to » / « to » pour exprimer le but : We called to confirm.',
    ],
    trap: '« look forward to » : « to » est ici une préposition → I look forward to <b>meeting</b> you.',
  },
  {
    id: 'relatifs',
    title: 'Les pronoms relatifs',
    emoji: '🪢',
    rule: 'Qui remplacent-ils ? Une personne, une chose, un lieu, un possesseur ?',
    points: [
      '<b>who</b> : personnes (sujet). <b>which</b> : choses. <b>that</b> : les deux (sans virgule).',
      '<b>whose</b> : possession → « the client <b>whose</b> order was late ».',
      '<b>where</b> : lieu ; <b>when</b> : moment.',
      '<b>whom</b> : personne complément, surtout après une préposition : « to whom ».',
    ],
    trap: 'Après une virgule, jamais « that » : « Our CEO, who founded the company… ».',
  },
  {
    id: 'condition',
    title: 'Conditionnel et « if »',
    emoji: '💭',
    rule: 'Associe correctement les temps des deux parties de la phrase.',
    points: [
      'Réel : If + présent, will + verbe → If you <b>order</b> today, you <b>will receive</b> it Monday.',
      'Hypothétique : If + prétérit, would + verbe → If we <b>had</b> more time, we <b>would finish</b>.',
      'Passé irréel : If + past perfect, would have + participe → If she <b>had applied</b>, she <b>would have got</b> the job.',
      'Forme élégante du TOEIC : « <b>Should</b> you have any questions, please call » = If you have any questions.',
    ],
    trap: 'Jamais « will » dans la partie avec if.',
  },
  {
    id: 'vocab',
    title: 'Questions de vocabulaire',
    emoji: '📚',
    rule: 'Les 4 réponses ont des sens différents : il faut le mot qui va avec le contexte (collocation).',
    points: [
      'Collocations : <b>meet</b> a deadline, <b>make</b> a decision, <b>place</b> an order, <b>conduct</b> a survey, <b>submit</b> a report.',
      '<b>raise</b> (augmenter qqch, + complément) ≠ <b>rise</b> (augmenter tout seul).',
      '<b>lend</b> (prêter) ≠ <b>borrow</b> (emprunter) ; <b>say</b> something ≠ <b>tell</b> someone.',
      'Apprends les mots par expressions entières, pas isolés : tes cartes de vocabulaire ont toutes une phrase d’exemple.',
    ],
    trap: '« make » (fabriquer, produire) ≠ « do » (activité, tâche) : make a profit, do business.',
  },
];

/* ---------- Partie 5 : phrases à compléter ---------- */

// { q, c: [4 choix], a: index de la bonne réponse, e: explication, t: fiche }
const P5 = [
  { q: 'The new software will make it easier for employees to track their ------- hours.', c: ['work', 'worked', 'working', 'works'], a: 2, t: 'formes', e: '« working hours » = heures de travail : le nom composé utilise la forme en -ing.' },
  { q: 'Ms. Tanaka was promoted because of her ------- performance last year.', c: ['except', 'exception', 'exceptional', 'exceptionally'], a: 2, t: 'formes', e: 'Devant le nom « performance », il faut un adjectif : exceptional.' },
  { q: 'Please read the safety instructions ------- before using the machine.', c: ['careful', 'carefully', 'care', 'caring'], a: 1, t: 'formes', e: 'Le trou modifie le verbe « read » : il faut un adverbe en -ly.' },
  { q: 'The ------- of the new branch is planned for early March.', c: ['open', 'opened', 'opening', 'opens'], a: 2, t: 'formes', e: 'Après « The » et avant « of », il faut un nom : the opening (l’ouverture).' },
  { q: 'All ------- must submit their documents by June 30.', c: ['apply', 'applicants', 'applications', 'applicable'], a: 1, t: 'formes', e: 'Ce sont des personnes qui soumettent des documents : applicants (candidats). « Applications » = candidatures.' },
  { q: 'The hotel staff were extremely ------- during our stay.', c: ['help', 'helpful', 'helpfully', 'helps'], a: 1, t: 'formes', e: 'Après le verbe « be » (were) et l’adverbe « extremely », il faut un adjectif : helpful.' },
  { q: 'Sales have increased ------- since the advertising campaign started.', c: ['significant', 'significance', 'significantly', 'signify'], a: 2, t: 'formes', e: 'Le trou modifie le verbe « increased » : adverbe → significantly.' },
  { q: 'Mr. Garcia is ------- for organizing the annual staff party.', c: ['responsible', 'responsibility', 'responsibly', 'respond'], a: 0, t: 'formes', e: '« be responsible for » = être responsable de. Après « is », il faut un adjectif.' },
  { q: 'Our company ------- in Toronto for more than twenty years.', c: ['is based', 'has been based', 'was basing', 'bases'], a: 1, t: 'temps', e: '« for more than twenty years » + situation qui dure encore → present perfect : has been based.' },
  { q: 'The board of directors ------- the proposal at last week’s meeting.', c: ['approves', 'has approved', 'approved', 'will approve'], a: 2, t: 'temps', e: '« last week » = moment passé terminé → prétérit : approved.' },
  { q: 'Ms. Wilson will call you as soon as she ------- back from lunch.', c: ['will come', 'comes', 'came', 'coming'], a: 1, t: 'temps', e: 'Après « as soon as » avec un sens futur, on utilise le présent : comes.' },
  { q: 'By the time the manager arrived, the meeting -------.', c: ['already ended', 'has already ended', 'had already ended', 'is already ending'], a: 2, t: 'temps', e: '« By the time » + prétérit : l’action antérieure est au past perfect (had ended).' },
  { q: 'The marketing team ------- on the new campaign at the moment.', c: ['works', 'is working', 'worked', 'has worked'], a: 1, t: 'temps', e: '« at the moment » → présent progressif : is working.' },
  { q: 'The museum ------- at 9:00 A.M. every day except Monday.', c: ['open', 'opens', 'is opening', 'opened'], a: 1, t: 'temps', e: 'Habitude (« every day ») + sujet singulier → présent simple : opens.' },
  { q: 'We ------- the results of the survey next Tuesday.', c: ['announced', 'have announced', 'will announce', 'announcing'], a: 2, t: 'temps', e: '« next Tuesday » → futur : will announce.' },
  { q: 'The list of participants ------- on the company website.', c: ['are posted', 'is posted', 'post', 'posting'], a: 1, t: 'accord', e: 'Le sujet est « The list » (singulier), et une liste est publiée (passif) : is posted.' },
  { q: 'Each of the new employees ------- a welcome package on the first day.', c: ['receive', 'receives', 'are receiving', 'have received'], a: 1, t: 'accord', e: '« Each of » + verbe au singulier : receives.' },
  { q: 'The information you requested ------- attached to this email.', c: ['is', 'are', 'were', 'be'], a: 0, t: 'accord', e: '« information » est indénombrable, donc singulier : is.' },
  { q: 'The annual report ------- by the finance department every January.', c: ['prepares', 'is prepared', 'is preparing', 'prepared'], a: 1, t: 'passif', e: 'Le rapport ne se prépare pas tout seul : passif au présent (every January) → is prepared.' },
  { q: 'Visitors are ------- to sign in at the front desk.', c: ['require', 'requiring', 'required', 'requirement'], a: 2, t: 'passif', e: '« be required to » = être tenu de : passif → required.' },
  { q: 'The new factory ------- near the airport next year.', c: ['will build', 'will be built', 'is building', 'builds'], a: 1, t: 'passif', e: 'L’usine sera construite (par quelqu’un) + next year → futur passif : will be built.' },
  { q: 'The keynote speech has ------- until 2:00 P.M. because of technical problems.', c: ['postponed', 'been postponed', 'postponing', 'postpone'], a: 1, t: 'passif', e: 'Le discours est reporté (il subit l’action) → present perfect passif : has been postponed.' },
  { q: 'The conference will take place ------- May 12 at the Grand Hotel.', c: ['in', 'at', 'on', 'by'], a: 2, t: 'prep', e: '« on » + date précise : on May 12.' },
  { q: 'Please return the signed contract ------- Friday at the latest.', c: ['until', 'by', 'since', 'during'], a: 1, t: 'prep', e: '« by » = au plus tard (une limite). « until » = jusqu’à (une durée continue).' },
  { q: 'The store will remain open ------- 10 P.M. during the holiday season.', c: ['by', 'until', 'within', 'at'], a: 1, t: 'prep', e: 'Une action qui continue jusqu’à un moment → until.' },
  { q: 'Refunds are processed ------- five business days.', c: ['within', 'among', 'between', 'across'], a: 0, t: 'prep', e: '« within » = dans un délai de.' },
  { q: 'Phones must be turned off ------- the presentation.', c: ['while', 'during', 'when', 'meanwhile'], a: 1, t: 'prep', e: '« during » + nom (the presentation). « while » serait suivi d’un sujet et d’un verbe.' },
  { q: 'Mr. Lopez is interested ------- joining the sales team.', c: ['on', 'for', 'in', 'at'], a: 2, t: 'prep', e: '« interested in » + verbe en -ing.' },
  { q: 'All products must comply ------- national safety standards.', c: ['to', 'with', 'by', 'for'], a: 1, t: 'prep', e: '« comply with » = se conformer à.' },
  { q: '------- the heavy rain, the outdoor concert went ahead as planned.', c: ['Although', 'Despite', 'Because', 'However'], a: 1, t: 'conj', e: 'Opposition + groupe nominal (the heavy rain) → Despite. « Although » serait suivi d’un sujet et d’un verbe.' },
  { q: 'The flight was cancelled ------- a mechanical problem.', c: ['because', 'due to', 'so that', 'although'], a: 1, t: 'conj', e: 'Cause + nom (a mechanical problem) → due to. « because » demande une phrase.' },
  { q: '------- the project was difficult, the team finished it on time.', c: ['Despite', 'In spite of', 'Although', 'Therefore'], a: 2, t: 'conj', e: 'Opposition + sujet + verbe (the project was) → Although.' },
  { q: 'The printer is out of order; -------, please use the one on the second floor.', c: ['therefore', 'although', 'unless', 'whereas'], a: 0, t: 'conj', e: 'Conséquence (l’imprimante est en panne, donc…) → therefore.' },
  { q: 'You cannot enter the building ------- you have an employee badge.', c: ['if', 'unless', 'so', 'because'], a: 1, t: 'conj', e: '« unless » = sauf si. Sens : tu ne peux pas entrer, sauf si tu as un badge.' },
  { q: 'The hotel offers free Wi-Fi. -------, breakfast is included in the room rate.', c: ['However', 'In addition', 'Instead', 'Otherwise'], a: 1, t: 'conj', e: 'On ajoute un avantage → In addition (de plus).' },
  { q: 'Ms. Patel asked us to send the files directly to -------.', c: ['she', 'her', 'hers', 'herself'], a: 1, t: 'pronoms', e: 'Après la préposition « to », il faut un pronom complément : her.' },
  { q: 'The clients were pleased with ------- new office design.', c: ['they', 'them', 'their', 'theirs'], a: 2, t: 'pronoms', e: 'Devant un nom (new office design) → adjectif possessif : their.' },
  { q: 'Mr. Chen prefers to review the contracts -------.', c: ['him', 'his', 'himself', 'he'], a: 2, t: 'pronoms', e: 'Pour insister sur le fait qu’il le fait lui-même → himself.' },
  { q: 'Our prices are lower than -------.', c: ['our competitors', 'our competitors’', 'competitor', 'competing'], a: 1, t: 'pronoms', e: 'On compare des prix avec des prix : « our competitors’ (prices) ».' },
  { q: 'This is the ------- hotel in the city.', c: ['more expensive', 'most expensive', 'expensive than', 'expensively'], a: 1, t: 'compar', e: '« the … in the city » → superlatif : the most expensive.' },
  { q: 'The new model is much ------- than the previous one.', c: ['light', 'lightest', 'lighter', 'more light'], a: 2, t: 'compar', e: '« than » → comparatif. Adjectif court : lighter.' },
  { q: 'Greenfield Foods is one of the ------- suppliers in the region.', c: ['large', 'larger', 'largest', 'largely'], a: 2, t: 'compar', e: '« one of the » + superlatif + nom pluriel : largest.' },
  { q: 'Applications should be submitted as ------- as possible.', c: ['soon', 'sooner', 'soonest', 'more soon'], a: 0, t: 'compar', e: '« as … as possible » : adjectif / adverbe à la forme simple → as soon as possible.' },
  { q: 'We look forward to ------- you at the trade fair.', c: ['see', 'seeing', 'seen', 'be seen'], a: 1, t: 'gerinf', e: 'Dans « look forward to », « to » est une préposition → verbe en -ing.' },
  { q: 'The company has decided ------- its operations to Asia.', c: ['expand', 'expanding', 'to expand', 'expanded'], a: 2, t: 'gerinf', e: '« decide » est suivi de to + verbe : to expand.' },
  { q: 'Employees should avoid ------- personal calls during working hours.', c: ['make', 'to make', 'making', 'made'], a: 2, t: 'gerinf', e: '« avoid » est suivi de -ing : making.' },
  { q: 'Before ------- the office, please turn off all the lights.', c: ['leave', 'leaving', 'to leave', 'left'], a: 1, t: 'gerinf', e: 'Après une préposition (before), verbe en -ing.' },
  { q: 'The manager suggested ------- the meeting to Thursday.', c: ['move', 'to move', 'moving', 'moved'], a: 2, t: 'gerinf', e: '« suggest » est suivi de -ing : moving.' },
  { q: 'The candidate ------- we interviewed yesterday has accepted the offer.', c: ['which', 'whom', 'whose', 'where'], a: 1, t: 'relatifs', e: 'Une personne, complément du verbe « interviewed » → whom (ou who / that).' },
  { q: 'We contacted the customer ------- order was delivered to the wrong address.', c: ['who', 'which', 'whose', 'that'], a: 2, t: 'relatifs', e: 'Possession (la commande du client) → whose.' },
  { q: 'The restaurant ------- we had lunch is near the station.', c: ['which', 'where', 'who', 'what'], a: 1, t: 'relatifs', e: 'Un lieu, et la phrase après est complète (we had lunch) → where.' },
  { q: 'If you ------- before noon, your package will arrive tomorrow.', c: ['order', 'will order', 'ordered', 'would order'], a: 0, t: 'condition', e: 'Condition réelle : If + présent, will + verbe. Jamais « will » après if.' },
  { q: 'If we had more staff, we ------- open on Sundays.', c: ['will', 'would', 'are', 'had'], a: 1, t: 'condition', e: 'If + prétérit (had) → would + verbe.' },
  { q: '------- you have any questions, please contact our customer service.', c: ['Should', 'Would', 'Unless', 'Whether'], a: 0, t: 'condition', e: '« Should you have… » = « If you have… ». Tournure formelle très fréquente au TOEIC.' },
  { q: 'The team worked late to ------- the deadline.', c: ['make', 'meet', 'do', 'reach out'], a: 1, t: 'vocab', e: 'Collocation : meet a deadline = respecter une échéance.' },
  { q: 'Please ------- your expense report by the end of the month.', c: ['submit', 'admit', 'commit', 'permit'], a: 0, t: 'vocab', e: '« submit a report » = remettre un rapport.' },
  { q: 'The company plans to ------- prices by 5 percent next year.', c: ['rise', 'raise', 'grow', 'arise'], a: 1, t: 'vocab', e: '« raise » + complément (prices). « rise » s’emploie sans complément : prices rise.' },
  { q: 'We would like to ------- an order for 200 units.', c: ['make', 'put', 'place', 'give'], a: 2, t: 'vocab', e: 'Collocation : place an order = passer une commande.' },
  { q: 'The research team will ------- a survey of 1,000 customers.', c: ['conduct', 'lead to', 'drive', 'take part'], a: 0, t: 'vocab', e: 'Collocation : conduct a survey = réaliser une enquête.' },
  { q: 'Could you ------- me your calculator for a minute?', c: ['borrow', 'lend', 'loan to', 'rent'], a: 1, t: 'vocab', e: '« lend » = prêter (à quelqu’un). « borrow » = emprunter.' },
  { q: 'The seminar was ------- attended, with over 500 participants.', c: ['good', 'well', 'better', 'best'], a: 1, t: 'formes', e: 'Devant un participe passé (attended), il faut un adverbe : well (bien).' },
  { q: 'The repairs were completed ------- than expected.', c: ['quick', 'quickly', 'more quickly', 'quickest'], a: 2, t: 'compar', e: '« than » → comparatif d’un adverbe : more quickly.' },
  { q: 'The shipment ------- yet, so we cannot confirm the delivery date.', c: ['didn’t arrive', 'hasn’t arrived', 'doesn’t arrive', 'won’t arrive'], a: 1, t: 'temps', e: '« yet » dans une phrase négative → present perfect : hasn’t arrived.' },
  { q: 'Mr. Kim, ------- has worked here for ten years, will lead the project.', c: ['that', 'which', 'who', 'whose'], a: 2, t: 'relatifs', e: 'Une personne, sujet du verbe, après une virgule → who (jamais « that » après une virgule).' },
  { q: 'The new policy will be ------- starting January 1.', c: ['effect', 'effective', 'effectively', 'effectiveness'], a: 1, t: 'formes', e: '« be effective » = entrer en vigueur. Après « be », il faut un adjectif.' },
];

/* ---------- Partie 6 : textes à trous ---------- */

// Chaque texte contient des trous [1], [2]… ; chaque question complète un trou.
const P6 = [
  {
    title: 'Email',
    text: 'To: All staff\nFrom: Facilities Department\nSubject: Parking lot repairs\n\nPlease note that the east parking lot [1] from Monday, April 4, to Friday, April 8. During this period, employees are asked to use the parking garage on Pine Street. [2], a free shuttle bus will run between the garage and our building every 15 minutes. [3]. We apologize for any [4] this may cause.',
    qs: [
      { c: ['closes', 'closed', 'will be closed', 'has closed'], a: 2, e: 'Les dates sont dans le futur (from Monday to Friday) et le parking subit l’action → futur passif : will be closed.' },
      { c: ['However', 'In addition', 'Instead', 'Otherwise'], a: 1, e: 'On ajoute une information pratique → In addition.' },
      { c: ['The repairs were completed last year.', 'Shuttle tickets can be bought online.', 'The shuttle will stop at the main entrance.', 'Pine Street is closed to traffic.'], a: 2, e: 'La phrase doit continuer logiquement l’information sur la navette gratuite : elle s’arrêtera à l’entrée principale. Les tickets payants contrediraient « free ».' },
      { c: ['inconvenient', 'inconvenience', 'inconveniently', 'convenience'], a: 1, e: 'Après « any », il faut un nom : inconvenience (le désagrément).' },
    ],
  },
  {
    title: 'Annonce',
    text: 'Harbor City Library is pleased to announce that its renovation is now [1]. The new building features a larger children’s area, a café, and twenty computer stations. To celebrate, the library [2] an open house on Saturday, May 21. Visitors can take guided tours and meet the staff. [3]. Admission is free, but we ask guests to [4] online so that we can plan refreshments.',
    qs: [
      { c: ['complete', 'completion', 'completely', 'completing'], a: 0, e: 'Après « is now », il faut un adjectif : complete (terminée).' },
      { c: ['held', 'has held', 'will hold', 'holding'], a: 2, e: 'L’événement aura lieu le 21 mai, dans le futur : will hold.' },
      { c: ['The library was built in 1965.', 'Children’s activities will also be offered throughout the day.', 'The café is closed on weekends.', 'Tours must be booked a month in advance.'], a: 1, e: 'On continue à décrire ce que les visiteurs peuvent faire pendant la journée portes ouvertes.' },
      { c: ['register', 'registration', 'registering', 'registered'], a: 0, e: '« ask someone to + base verbale » : to register.' },
    ],
  },
  {
    title: 'Lettre à un client',
    text: 'Dear Mr. Novak,\n\nThank you for your recent order. Unfortunately, the desk chair you selected is temporarily out of stock. We expect to receive new stock [1] two weeks. If you prefer not to wait, we can offer you a similar model at the same price. [2], you may cancel your order and receive a full refund. Please let us know which option you [3] by replying to this email. [4].\n\nSincerely,\nAnna Ruiz, Customer Service',
    qs: [
      { c: ['within', 'since', 'during', 'by'], a: 0, e: '« within two weeks » = dans un délai de deux semaines.' },
      { c: ['Therefore', 'Alternatively', 'Similarly', 'As a result'], a: 1, e: 'On propose une autre possibilité → Alternatively (sinon, autrement).' },
      { c: ['prefer', 'preferring', 'preference', 'preferable'], a: 0, e: 'Il faut un verbe conjugué après le sujet « you » : prefer.' },
      { c: ['We apologize for the delay and thank you for your patience.', 'Your chair was delivered yesterday.', 'Our store opened in 1998.', 'Please pay the remaining balance.'], a: 0, e: 'Formule de fin logique pour un client qui doit attendre. Les autres contredisent le texte.' },
    ],
  },
  {
    title: 'Note de service',
    text: 'MEMO\nTo: Sales team\nRe: New expense policy\n\nStarting next month, all travel expenses must be [1] through the new online system. Paper forms will no longer be accepted. Please attach a photo of each receipt [2] you submit a claim. Claims are usually approved within five days. [3]. If you have any questions about the system, please contact Mark Ellis in the accounting department, who [4] the training sessions.',
    qs: [
      { c: ['submit', 'submitted', 'submitting', 'submission'], a: 1, e: 'Après « must be », il faut un participe passé (passif) : submitted.' },
      { c: ['when', 'during', 'despite', 'unless'], a: 0, e: '« when you submit a claim » = au moment où tu soumets. « during » serait suivi d’un nom.' },
      { c: ['Approved amounts are added to your next paycheck.', 'Paper forms are available at reception.', 'The system was cancelled last week.', 'Receipts are not necessary.'], a: 0, e: 'Logique après l’approbation : le remboursement arrive sur la fiche de paie. Les autres contredisent le mémo.' },
      { c: ['lead', 'are leading', 'is leading', 'leading'], a: 2, e: '« who » remplace Mark (3e personne du singulier) : is leading. « lead » et « are leading » ne s’accordent pas, « leading » seul n’est pas un verbe conjugué.' },
    ],
  },
];

/* ---------- Partie 7 : compréhension écrite ---------- */

const P7 = [
  {
    title: 'Annonce d’emploi',
    text: 'ADMINISTRATIVE ASSISTANT — Brightline Consulting\n\nBrightline Consulting is looking for a full-time administrative assistant for its Boston office. Responsibilities include answering phones, scheduling meetings, and preparing reports for senior managers.\n\nRequirements:\n• At least two years of office experience\n• Excellent knowledge of spreadsheet software\n• Strong communication skills; Spanish is a plus\n\nWe offer a competitive salary, health insurance, and 20 days of paid vacation. To apply, send your résumé and a cover letter to jobs@brightline.com by March 15. Only candidates selected for an interview will be contacted.',
    qs: [
      { q: 'What is the purpose of the notice?', c: ['To announce a new office', 'To advertise a job opening', 'To describe a training course', 'To introduce a manager'], a: 1, e: 'Le texte décrit un poste, des exigences et comment postuler : c’est une offre d’emploi.' },
      { q: 'What is NOT mentioned as a requirement?', c: ['Office experience', 'Computer skills', 'A university degree', 'Communication skills'], a: 2, e: 'Les questions NOT : élimine ce qui est cité. Le diplôme universitaire n’apparaît nulle part.' },
      { q: 'What is suggested about the Spanish language?', c: ['It is required', 'It is useful but optional', 'It will be taught', 'It is spoken in the office'], a: 1, e: '« Spanish is a plus » = c’est un atout, pas une obligation.' },
    ],
  },
  {
    title: 'Échange de messages',
    text: 'Lena Fischer [9:12 A.M.]: Hi Tom, are you still at the client’s office?\nTom Grant [9:14 A.M.]: Yes, the meeting started late. Why?\nLena Fischer [9:15 A.M.]: The projector in Room B isn’t working, and I have a presentation at 10.\nTom Grant [9:16 A.M.]: Have you tried Room D? It’s usually free on Tuesdays.\nLena Fischer [9:18 A.M.]: Good idea. I’ll check with reception.\nTom Grant [9:19 A.M.]: Let me know if you need my laptop adapter. It’s in my top drawer.',
    qs: [
      { q: 'What problem does Ms. Fischer mention?', c: ['She is late for a meeting', 'Some equipment is not working', 'She lost her laptop', 'A client cancelled'], a: 1, e: '« The projector in Room B isn’t working » : un équipement est en panne (reformulation).' },
      { q: 'At 9:16 A.M., what does Mr. Grant mean when he writes, "It’s usually free on Tuesdays"?', c: ['The room costs nothing', 'The room is probably available', 'He has a day off', 'The reception is closed'], a: 1, e: 'Ici « free » = libre, disponible (pas gratuit). Question de sens en contexte, très fréquente.' },
      { q: 'What does Mr. Grant offer?', c: ['To give the presentation', 'To call reception', 'To lend an item', 'To come back early'], a: 2, e: 'Il propose son adaptateur, rangé dans son tiroir : il prête un objet.' },
    ],
  },
  {
    title: 'Email client',
    text: 'To: customerservice@urbanhome.com\nFrom: r.silva@mailbox.com\nSubject: Order #48213\n\nHello,\n\nI ordered a set of four dining chairs on your website on June 2. The package arrived yesterday, but one of the chairs has a broken leg. The other three are in perfect condition, and I am very happy with their quality.\n\nI would like to receive a replacement for the damaged chair rather than a refund. I have attached photos of the damage. Please let me know whether I need to return the broken chair or if a courier will collect it.\n\nBest regards,\nRosa Silva',
    qs: [
      { q: 'Why did Ms. Silva write the email?', c: ['To place an order', 'To report a damaged item', 'To cancel a delivery', 'To ask about prices'], a: 1, e: 'Elle signale une chaise abîmée : « one of the chairs has a broken leg ».' },
      { q: 'What does Ms. Silva want?', c: ['A full refund', 'A discount on her next order', 'A new chair', 'Four new chairs'], a: 2, e: '« a replacement for the damaged chair rather than a refund » : elle veut une chaise de remplacement.' },
      { q: 'What did Ms. Silva include with her email?', c: ['A receipt', 'Pictures', 'A return form', 'Her address'], a: 1, e: '« I have attached photos » : photos = pictures (synonyme).' },
    ],
  },
  {
    title: 'Article',
    text: 'GREENVILLE (May 3) — Riverside Bakery, a family business founded in 1987, will open its third location next month on Elm Avenue. Owner Maria Costa says the new shop will be larger than the first two and will include a seating area for 40 customers.\n\n"Our customers kept asking for a place to sit and enjoy their coffee," Ms. Costa explained. The bakery is also hiring twelve new employees, including two experienced pastry chefs.\n\nThe Elm Avenue shop will be open seven days a week from 6:30 A.M. to 7 P.M. A grand opening celebration with free samples is planned for June 10.',
    qs: [
      { q: 'What is the article mainly about?', c: ['A bakery’s history', 'The opening of a new shop', 'A cooking competition', 'Changes to opening hours'], a: 1, e: 'L’idée principale : l’ouverture d’une troisième boutique.' },
      { q: 'Why will the new location have a seating area?', c: ['Because of customer requests', 'To host events', 'Because the rent is cheaper', 'To sell more bread'], a: 0, e: '« Our customers kept asking for a place to sit » → à la demande des clients.' },
      { q: 'What will happen on June 10?', c: ['Job interviews', 'A celebration', 'The shop will close', 'A new chef will arrive'], a: 1, e: '« A grand opening celebration… is planned for June 10 ».' },
    ],
  },
];

/* ---------- Partie 2 : questions-réponses (audio) ---------- */

// q : la question entendue ; r : les 3 réponses entendues ; a : la bonne.
const P2 = [
  { q: 'Where is the nearest post office?', r: ['At three o’clock.', 'Just around the corner.', 'Yes, I posted it.'], a: 1, e: '« Where » → un lieu. « posted » est un piège sonore (post office / posted).' },
  { q: 'When does the training session start?', r: ['In Room 4.', 'Mr. Lee is leading it.', 'Right after lunch.'], a: 2, e: '« When » → un moment : right after lunch.' },
  { q: 'Who is in charge of the budget this year?', r: ['Ms. Harris, I think.', 'It’s quite expensive.', 'Charge it to my account.'], a: 0, e: '« Who » → une personne. « Charge » répète un son de la question : piège.' },
  { q: 'Why was the meeting cancelled?', r: ['Because the director is sick.', 'Yes, it was.', 'At the main office.'], a: 0, e: '« Why » → une raison, souvent avec « because ».' },
  { q: 'How long will the repairs take?', r: ['About two days.', 'He’s very tall.', 'By taxi.'], a: 0, e: '« How long » → une durée.' },
  { q: 'Would you like some coffee?', r: ['I like the color.', 'Thanks, I just had some.', 'It’s in the kitchen drawer.'], a: 1, e: 'Proposition → accepter ou refuser poliment. « Thanks, I just had some » = refus poli.' },
  { q: 'Did you send the invoice to the client?', r: ['Yes, this morning.', 'A new client.', 'It costs fifty dollars.'], a: 0, e: 'Question fermée (Did…?) → oui / non + précision.' },
  { q: 'Which printer should I use?', r: ['The one by the window.', 'Print three copies.', 'Yes, you should.'], a: 0, e: '« Which » → un choix : « the one… ».' },
  { q: 'Could you help me move these boxes?', r: ['Sure, where do they go?', 'We moved last year.', 'They’re cardboard.'], a: 0, e: 'Demande d’aide → accepter : « Sure… ». « moved » est un piège.' },
  { q: 'Isn’t the store open on Sundays?', r: ['No, only on weekdays.', 'A grocery store.', 'Please open the window.'], a: 0, e: 'Question négative : réponds comme à une question normale. « Only on weekdays » = pas le dimanche.' },
  { q: 'Should we take a taxi or the subway?', r: ['Yes, we should.', 'The subway is faster at this hour.', 'I took it yesterday.'], a: 1, e: 'Question à choix (A or B) → jamais « yes / no ». On choisit une option.' },
  { q: 'How much is a ticket to the museum?', r: ['Twelve dollars for adults.', 'Many people.', 'At the entrance.'], a: 0, e: '« How much » → un prix.' },
  { q: 'The report is due tomorrow, isn’t it?', r: ['Actually, it’s due on Friday.', 'Yes, he reported it.', 'I do too.'], a: 0, e: 'Question-tag → confirmer ou corriger. Ici on corrige : c’est pour vendredi.' },
  { q: 'Where can I find the conference schedule?', r: ['It’s posted on the website.', 'Next Tuesday.', 'The conference was great.'], a: 0, e: '« Where » → un endroit : sur le site web.' },
  { q: 'What time does your flight leave?', r: ['From Gate 12.', 'At 6:45.', 'For two weeks.'], a: 1, e: '« What time » → une heure précise.' },
  { q: 'Who should I give this form to?', r: ['Leave it with the receptionist.', 'It’s a new form.', 'I gave it yesterday.'], a: 0, e: 'Réponse indirecte mais logique : laisse-le à la réceptionniste (= c’est à elle qu’il faut le donner).' },
  { q: 'Why don’t we order lunch from the Italian place?', r: ['Because it was closed.', 'Good idea, I’ll call them.', 'At noon.'], a: 1, e: '« Why don’t we… ? » est une SUGGESTION, pas une vraie question sur la raison → « Good idea ».' },
  { q: 'Has the new manager started yet?', r: ['She starts next Monday.', 'Yes, it’s a new car.', 'He managed well.'], a: 0, e: 'Réponse logique : pas encore, elle commence lundi.' },
  { q: 'Can I pay by credit card?', r: ['Of course, we accept all cards.', 'A birthday card.', 'It’s free parking.'], a: 0, e: 'Demande → accepter / refuser. « card » répété dans B : piège.' },
  { q: 'How did the presentation go?', r: ['It went very well, thanks.', 'By bus.', 'Next to the screen.'], a: 0, e: '« How did … go? » = comment ça s’est passé.' },
];

/* ---------- Parties 3 et 4 : conversations et exposés (audio) ---------- */

// lines : [voix, texte] ; M = homme, W = femme, N = narrateur / annonce.
const P34 = [
  {
    part: 'p3',
    title: 'Au bureau',
    lines: [
      ['W', 'Hi Daniel, do you know if the new laptops have arrived? The supplier said they would be delivered this morning.'],
      ['M', 'They came about an hour ago, but there are only eight boxes. We ordered ten.'],
      ['W', 'Oh no. The new interns start on Monday and they all need a computer.'],
      ['M', 'I’ll call the supplier right now and ask them to send the other two by Friday.'],
    ],
    qs: [
      { q: 'What are the speakers discussing?', c: ['A delivery of equipment', 'A job interview', 'A training schedule', 'A broken printer'], a: 0, e: 'Ils parlent de la livraison des ordinateurs portables (equipment).' },
      { q: 'What problem does the man mention?', c: ['The laptops are damaged', 'The order is incomplete', 'The delivery is late', 'The price is wrong'], a: 1, e: 'Huit cartons au lieu de dix : la commande est incomplète.' },
      { q: 'What will the man do next?', c: ['Cancel the order', 'Contact a supplier', 'Meet the interns', 'Buy new laptops'], a: 1, e: '« I’ll call the supplier right now » → contacter le fournisseur.' },
    ],
  },
  {
    part: 'p3',
    title: 'Au restaurant',
    lines: [
      ['M', 'Good evening, I have a reservation for four people under the name Romero, at seven thirty.'],
      ['W', 'Let me check, Mr. Romero. Yes, I see it. Your table is on the terrace, but it’s getting a little cold outside.'],
      ['M', 'In that case, would it be possible to sit inside?'],
      ['W', 'Of course. We have a table by the window. It will be ready in about ten minutes. You can wait at the bar if you like.'],
    ],
    qs: [
      { q: 'Where most likely are the speakers?', c: ['At a hotel', 'At a restaurant', 'At an airport', 'At a theater'], a: 1, e: 'Réservation pour 4, table, terrasse, bar : un restaurant.' },
      { q: 'What does the man ask for?', c: ['A different table', 'A menu', 'A later reservation', 'The bill'], a: 0, e: 'Il demande à s’asseoir à l’intérieur, donc une autre table.' },
      { q: 'What does the woman suggest?', c: ['Coming back tomorrow', 'Waiting at the bar', 'Ordering now', 'Sitting on the terrace'], a: 1, e: '« You can wait at the bar if you like ».' },
    ],
  },
  {
    part: 'p3',
    title: 'Ressources humaines',
    lines: [
      ['W', 'Mark, have you had time to look at the résumés for the accountant position?'],
      ['M', 'Yes, I’ve gone through all of them. I think three candidates really stand out.'],
      ['W', 'Great. Can we schedule interviews for next week? I’m away on Thursday, though.'],
      ['M', 'No problem. I’ll book them for Tuesday and Wednesday and send you the times this afternoon.'],
    ],
    qs: [
      { q: 'What position are the speakers trying to fill?', c: ['Sales manager', 'Accountant', 'Receptionist', 'Engineer'], a: 1, e: '« the résumés for the accountant position ».' },
      { q: 'What does the woman say about Thursday?', c: ['She will be away', 'It is a holiday', 'Interviews are planned', 'The office is closed'], a: 0, e: '« I’m away on Thursday » = elle sera absente.' },
      { q: 'What will the man send this afternoon?', c: ['A job offer', 'Interview times', 'A contract', 'Résumés'], a: 1, e: '« send you the times this afternoon » → les horaires des entretiens.' },
    ],
  },
  {
    part: 'p4',
    title: 'Annonce à l’aéroport',
    lines: [
      ['N', 'Attention passengers on Skyway flight 208 to Madrid. Due to bad weather in Madrid, this flight has been delayed. The new departure time is 4:15 P.M. The gate has also changed from Gate 7 to Gate 15. Passengers can collect a meal voucher at the Skyway service desk near Gate 10. We apologize for the inconvenience.'],
    ],
    qs: [
      { q: 'Why has the flight been delayed?', c: ['A technical problem', 'Bad weather', 'A staff shortage', 'Heavy traffic'], a: 1, e: '« Due to bad weather in Madrid ».' },
      { q: 'Which gate will the flight leave from?', c: ['Gate 7', 'Gate 10', 'Gate 15', 'Gate 208'], a: 2, e: 'La porte change de 7 à 15. Attention aux chiffres-pièges (10 = comptoir, 208 = vol).' },
      { q: 'What can passengers get at the service desk?', c: ['A new ticket', 'A refund', 'A meal voucher', 'A hotel room'], a: 2, e: '« collect a meal voucher at the Skyway service desk ».' },
    ],
  },
  {
    part: 'p4',
    title: 'Message téléphonique',
    lines: [
      ['N', 'Hello, this is Karen from Bright Smile Dental Clinic calling for Mr. Thomas Reed. I’m calling to remind you of your appointment with Dr. Patel tomorrow at 9 A.M. Please remember to bring your insurance card. If you need to change the time, call us back at 555-0143 before 5 P.M. today. Thank you, and have a nice day.'],
    ],
    qs: [
      { q: 'What is the purpose of the call?', c: ['To confirm a payment', 'To remind someone of an appointment', 'To offer a job', 'To cancel a service'], a: 1, e: '« I’m calling to remind you of your appointment ».' },
      { q: 'What should Mr. Reed bring?', c: ['A form', 'An insurance card', 'A prescription', 'Cash'], a: 1, e: '« bring your insurance card ».' },
      { q: 'Why might Mr. Reed call back?', c: ['To change the time', 'To ask for directions', 'To pay a bill', 'To speak to Dr. Patel'], a: 0, e: '« If you need to change the time, call us back ».' },
    ],
  },
  {
    part: 'p4',
    title: 'Visite guidée',
    lines: [
      ['N', 'Welcome to the Lakeside Chocolate Factory. My name is Paul, and I’ll be your guide today. Our tour lasts about forty-five minutes. First, we’ll see how cocoa beans are roasted, and then we’ll visit the packaging area. For safety reasons, please don’t touch any of the machines. At the end of the tour, everyone will receive a free box of chocolates, and our gift shop offers a ten percent discount for visitors today.'],
    ],
    qs: [
      { q: 'Who most likely is the speaker?', c: ['A factory worker', 'A tour guide', 'A shop manager', 'A chef'], a: 1, e: '« I’ll be your guide today ».' },
      { q: 'What are listeners asked not to do?', c: ['Take photos', 'Touch the machines', 'Eat chocolate', 'Leave the group'], a: 1, e: '« please don’t touch any of the machines ».' },
      { q: 'What will listeners receive at the end?', c: ['A discount coupon', 'A gift', 'A recipe book', 'A ticket'], a: 1, e: '« a free box of chocolates » = un cadeau (reformulation).' },
    ],
  },
];

/* ---------- Toutes les questions, à plat ---------- */

const pad2 = (n) => String(n).padStart(2, '0');

export const QUESTIONS = [
  ...P2.map((x, i) => ({ id: `p2-${pad2(i + 1)}`, part: 'p2', audio: [['W', x.q], ['M', `A. ${x.r[0]}`], ['M', `B. ${x.r[1]}`], ['M', `C. ${x.r[2]}`]], q: 'Écoute la question et choisis la meilleure réponse.', c: ['A', 'B', 'C'], a: x.a, e: x.e, script: `${x.q}\n(A) ${x.r[0]}\n(B) ${x.r[1]}\n(C) ${x.r[2]}` })),
  ...P34.flatMap((set, si) =>
    set.qs.map((x, qi) => ({ id: `${set.part}-${pad2(si + 1)}-${qi + 1}`, part: set.part, group: `${set.part}-${si + 1}`, title: set.title, audio: set.lines, q: x.q, c: x.c, a: x.a, e: x.e, script: set.lines.map(([v, t]) => (v === 'N' ? t : `${v === 'W' ? 'Woman' : 'Man'}: ${t}`)).join('\n') })),
  ),
  ...P5.map((x, i) => ({ id: `p5-${pad2(i + 1)}`, part: 'p5', ...x })),
  ...P6.flatMap((set, si) => set.qs.map((x, qi) => ({ id: `p6-${si + 1}-${qi + 1}`, part: 'p6', group: `p6-${si + 1}`, title: set.title, passage: set.text, blank: qi + 1, q: `Complète le trou [${qi + 1}].`, ...x }))),
  ...P7.flatMap((set, si) => set.qs.map((x, qi) => ({ id: `p7-${si + 1}-${qi + 1}`, part: 'p7', group: `p7-${si + 1}`, title: set.title, passage: set.text, ...x }))),
];
